# This is the configuration file with some standard settings.
# Each subpackage has its own section here.

[specgen]
cog.integration_range_factor                 = 1e-3 # in order to obtain the equivalent width of a line with a-priori unknown strength, will be integrate
cog.integration_resolution                   = 1e-2 # wavelength sampling in Angstrom
